### ISSUE TITLE
Fix warning in origin databases 

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#101]
Adlercreutzia_equolifaciens_DSM_19450
/home/td/Projects/MeMoMe/src/origin_databases.py:50: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ModelSEED = pd.read_table(db_path)

![image](https://github.com/Porthmeus/MeMoMe/assets/7808379/2bddb28f-6c8b-40f1-8bad-255c2dabb8f5)

**Comment by DafniGi** [comment]
Check out #143.
