### ISSUE TITLE
command does not do any tests if the data bases are already downloaded

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#11]
1. Download databases
2. run tests

Expected behavior:
Tests are executed

Current behavior: 
Tests are not executed

**Comment by Unaimend** [comment]
@Porthmeus not reproducible
![image](https://user-images.githubusercontent.com/7808379/219679244-85169041-bea2-4c23-814c-b136a74bfa39.png)

**Comment by Porthmeus** [comment]
Same here - don't know what the issue was in the first place.
