### ISSUE TITLE
Annotation count is reporting wrong numbers when mod.annotate()

### ISSUE THREAD

**Issue by Porthmeus** [Porthmeus/MeMoMe#132]

**Comment by Unaimend** [comment]
Do you have a test case?

**Comment by Porthmeus** [comment]
Minimal example:
`import cobra as cb
from src.MeMoMetabolite import MeMoMetabolite
from src.MeMoModel import MeMoModel

#this_directory = Path(__file__).parent
#dat = this_directory.joinpath("../manually_merged_models")
mod = cb.io.load_model("textbook")
mod = MeMoModel.fromModel(mod)
len(mod.metabolites)
sum([x._inchi_string == None for x in mod.metabolites])
mod.annotate()
sum([x._inchi_string == None for x in mod.metabolites])
`

**Comment by Unaimend** [comment]
What is the expected result of this test case?

**Comment by Unaimend** [comment]
len(mod.metabolites) == sum([x._inchi_string == None for x in mod.metabolites]) after annotation?

**Comment by Unaimend** [comment]
I guess it should be mod.annotate == len(mod.metabolites)

**Comment by Unaimend** [comment]
![image](https://github.com/Porthmeus/MeMoMe/assets/7808379/e0751b2a-589a-48ff-a4f3-8b6d402bb630)
Currently we annotate more inchis then there are mtabolites

**Comment by Unaimend** [comment]
```
ORIG DB BiGG
BiGG: Annotated inchis 0, annotated dbs 11, annotated names 11
There was an error during in RDkit (1)
There was an error during in RDkit (1)
ChEBI: Annotated inchis 72, annotated dbs 0, annotated names 0
ModelSEED: Annotated inchis 4, annotated dbs 72, annotated names 72
VMH: Annotated inchis 0, annotated dbs 0, annotated names 0
Total: Annotated inchis 76, annotated dbs 83, annotated names 83 

BiGG: Annotated inchis 0, annotated dbs 5, annotated names 5
ChEBI: Annotated inchis 0, annotated dbs 0, annotated names 0
ModelSEED: Annotated inchis 1, annotated dbs 2, annotated names 2
VMH: Annotated inchis 0, annotated dbs 0, annotated names 0
Total: Annotated inchis 77, annotated dbs 90, annotated names 90 

BiGG: Annotated inchis 0, annotated dbs 0, annotated names 0
ChEBI: Annotated inchis 0, annotated dbs 0, annotated names 0
ModelSEED: Annotated inchis 0, annotated dbs 0, annotated names 0
VMH: Annotated inchis 0, annotated dbs 0, annotated names 0
Total: Annotated inchis 77, annotated dbs 90, annotated names 90 

Annoatted Annotated inchis 77, annotated dbs 90, annotated names 90
Amount of unannotated inchis after Annotation 0
.
----------------------------------------------------------------------
Ran 1 test in 12.846s
```

**Comment by Porthmeus** [comment]
But in general this looks really good, as it does exactly what we would expect - namely annotating the crossreferences sequentially. And the extra Inchi annotation might result from the fact, that ModelSeed has slightly more information in its inchis, thus a more complex inchi string, which would result in reannotation of the inchi and a count in that field.
