### ISSUE TITLE
Wrong annotation count 

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#134]
I think I spotted a small bug, but might be an ommission on purpose in line 105-107 for MeMoModel.py - @Unaimend  please confirm.

_Originally posted by @Porthmeus in https://github.com/Porthmeus/MeMoMe/pull/100#pullrequestreview-2009265752_

**Comment by Porthmeus** [comment]
This should be fixed, should it not? Please close if so... I don't remember.

**Comment by Unaimend** [comment]
@Porthmeus Is it fixed now?

**Comment by Porthmeus** [comment]
The fix is implemented in #149, as soon as it is merged, this can be closed.
