### ISSUE TITLE
keep1ToMany not respected 

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#140]
Test case thats failing 
![image](https://github.com/Porthmeus/MeMoMe/assets/7808379/24cfd398-a446-432b-a9a6-b2c31ab33c84)
 
 
![image](https://github.com/Porthmeus/MeMoMe/assets/7808379/65472927-2a99-4a96-a6a0-2c50b6020a89)
Output of the matching.

You can see that keep1ToMany is false but the output contains one to many matches. I think they have been matched on inchi so the matchInchi function does not properly respect the parameter

_Originally posted by @Unaimend in https://github.com/Porthmeus/MeMoMe/issues/100#issuecomment-2098331286_

**Comment by Unaimend** [comment]
![image](https://github.com/Porthmeus/MeMoMe/assets/7808379/6f53afa6-8760-4bb5-8361-9522a3f5fe43)
But there is a test case for that

**Comment by Unaimend** [comment]
The above mentioned test case does indeed miss this case

**Comment by Porthmeus** [comment]
tried and can't replicate the problem - please check again:
```
from pathlib import Path
from src.MeMoMetabolite import MeMoMetabolite
this_directory = Path("tests/")
dat = this_directory.joinpath("dat")
mod_path = dat.joinpath("e_coli_core.xml")
mod = MeMoModel.fromPath(mod_path)
mod.annotate()
res = mod.match(mod, keep1ToMany= False)
```
