### ISSUE TITLE
Annotate and matching runs into errors 

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#161]
General issue for matching and annotate relate stuff

**Comment by Porthmeus** [comment]
Do you have an example to replicate the error?

**Comment by Unaimend** [comment]
This issue was just for you. You wanted a general issue for everything annotation/matching related

**Comment by Porthmeus** [comment]
Did I? Sounds stupid to me... will close it again... sorry for the brain fart.
