### ISSUE TITLE
Re-enable tests

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#174]
I disabled those test because sth. weird is going with the isolation between test cases.
I do not think that we really have a bug
![image](https://github.com/user-attachments/assets/48a6e395-3a35-4105-8fc6-6093b1099b1c)
Look at https://github.com/Porthmeus/MeMoMe/pull/170 for details on how those tests influence each other

**Comment by Porthmeus** [comment]
Was a problem in the logger
