### ISSUE TITLE
Write a small descrition of how to add models

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#20]
` in the met_matches.csv file, please change the columns to M1, M2 (according to the prefixes of the model files). For the protons added columns, indicate where (ProtonsAdd_M1, for example). We will keep this scheme for all other models we add to the project as we go on and it will enable us to do automatic testing.`

Maybe like three line what to consider when adding a model to the repo

**Comment by Porthmeus** [comment]
Haven't you done that? Just corrected some minor things on the file... If so, please close
