### ISSUE TITLE
Remove compartment function

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#22]
![image](https://user-images.githubusercontent.com/7808379/225691995-3e9fc3e3-3c6f-452d-bf05-34c850f99f41.png)
id and name contain the compartment, that's a problem for using those as identifiers e.g. looking them up in a DB.

This seems to only relevant for the compound name as SBML has an extra field for the chemical formula
![image](https://user-images.githubusercontent.com/7808379/225700181-7de9c91c-52c3-4f6b-abcc-fcbfa1db273c.png)

**Comment by Unaimend** [comment]
Implemented by a621c20

**Comment by Porthmeus** [comment]
Should be implemented already, @SteFlor I believe it was you, could you check once more on `main` and close this issue if appropiate

**Comment by SteFlor** [comment]
I was convince it was closed already, closing it now! :)
