### ISSUE TITLE
Behavior of met.getAnnotationString()

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#23]
The code at 
https://github.com/Porthmeus/MeMoMe/blob/7aaf56576e9ccd43dca96ba8dc7702b350f44035/src/parseMetaboliteInfoFromSBML.py#L36-L42

specifically, line 40. What is that supposed to do?

Because for whatever reason the function `met.getAnnitationString()` returns a list with an empty string  i.e. [""] when no annotation source is present. Thus we run into len(urls) >0. I suppose that is not the wanted behavior.

To reproduce load M2_bacter.. and set a breakpoint at L42 in the aforementioned file or look the content of `urls` for the first metab.

**Comment by Porthmeus** [comment]
Probably put a simple `if url != ""` somewhere in the code to circumvent unwanted behavior. However, we want to extract all metabolites in that list, which are also in the model. Thus it makes sense to keep them in the list, even if there is no annotation for in the model. It would be probably better to replace "" with None-type though.
