### ISSUE TITLE
Do a recursive database search

### ISSUE THREAD

**Issue by Porthmeus** [Porthmeus/MeMoMe#29]
There might be the case that a model consists of metabolites from different databases, in that case we need to identify which metabolite is derived from which database.

- [x] go through a list of metabolite IDs and try to find it in a one of the databases downloaded [here](https://github.com/Porthmeus/MeMoMe/blob/master/src/download_db.py)

Points for consideration: Ids are not necessarily unique to one database and it we need to take care to get the right database (which is not trivial). Again discussion will be key to solve this problem.

relates to #21

**Comment by DafniGi** [comment]
Check out https://github.com/Porthmeus/MeMoMe/pull/38

**Comment by Unaimend** [comment]
Kind of relates to https://github.com/Porthmeus/MeMoMe/issues/102
