### ISSUE TITLE
Is there way of checking in Python if an SBML file is valid 

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#33]
Currently, we get weird errors somewhere in the parseMEtaboliteInfo function if we supply an invalid SBML file.
This is not very user-friendly.

**Comment by Porthmeus** [comment]
Yes several: 

1. `cobra.io.validate_sbml_model()`  is the simplest
2.  libsbml implements a validator as well, but it is less simple to use - check the documentation [here](https://sbml.org/software/libsbml/5.18.0/docs/formatted/python-api/classlibsbml_1_1_s_b_m_l_validator.html#a67a3acf4ecaf8d5bec066ee34fb3ccad)
3. You might check out [Memote](https://memote.io/) which is also python based and has an elaborate system to test metabolic models.

**Comment by Porthmeus** [comment]
Closes with #41 
There is a function using the libsbml validator in the parseMetaboliteInfoFromSBML.py
