### ISSUE TITLE
CPD extraction code currently misidentifies IDs from Dafnis models

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#34]
`M_cpd00003__91__c__93__` are identified as cpd as well as big because they start with M_ like BIGG but also contain cpd***** like modelSeed. Please fix

**Comment by Unaimend** [comment]
The same problem should happen with the recon ids

**Comment by Porthmeus** [comment]
Good that you mention it - I just realized the issue exists. Could we create a table of all kinds of metabolite id schemes we encounter while working with different models in the `test/dat/` directory? This would give us test cases to test the functions we write for name handling.

**Comment by Porthmeus** [comment]
Is this still relevant? Could you point me to a function to fix the problem?

**Comment by Unaimend** [comment]
No idea tbh.
