### ISSUE TITLE
Implement DataBaseManager

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#45]
This class should manage the download of all databases, it also should contain a reference to each database for ease of access in other places of the code

```
class DBM:
    bigg: pd.DataFrame = ....
    .....
    
    
  
#### Usage
# get bigg database
bigg = DBM.bigg
# use the database for sth
```

This will make it super easy to work with all the databases in the code, instead of having to open them by the path which is quite error prone

**Comment by Porthmeus** [comment]
We should also think about a `update()` function, especially for Dafnis code on the BIGG database. This would shorten the download process a lot, once we have a base file for the database.

**Comment by Unaimend** [comment]
Done in #90
