### ISSUE TITLE
Fix GitHub Actions.

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#64]
Currently, we do not download the databases during GHA (GitHub Actions), this results in errors during the test. It should be possible to download the data and cache it so you don't have to do it every time BUT this solution will not be feasible for PBC since it is too big. 

I think it makes sense to implement a flag like `--skip-pbc` to ignore this database during GHA. This ofc, is a suboptimal solution
Additionally, we still should write tests that use PBC if we either can figure out how to skip those during GHA or just use the above flag and live with the fact that those tests don't do anything on GHA. So we are still able to test locally 

Another hacky solution might be to ALWAYS just download them if we cannot find the databases locally, similar to how the chebi db is currently handled in the bulk annotation

**Comment by Porthmeus** [comment]
I guess this is a good discussion point for a meeting. I will put it on the agenda!
