### ISSUE TITLE
Handling reactions which use duplicated metabolites within one model

### ISSUE THREAD

**Issue by Porthmeus** [Porthmeus/MeMoMe#70]
The issue relates to #53
If duplicate reactions exist, which use the same metabolites, but different metabolite ids there are three cases which can occur.
    1. the reactions are identical → simply delete one
    3. the reactions are identical, but annotation, GPR and/or bounds differ - we decided on the following → annotations will simply be merged, GPR will be merged with an OR, bounds will be adjusted to the most liberal ones
    4. reactions are not identical, because protonation states differ → take the protonation state which is mostly prevalent in all models reactions. If there is a draw, take the first lexicographical one

**Comment by Unaimend** [comment]
https://github.com/Porthmeus/MeMoMe/tree/Bram-Issue-53

**Comment by Unaimend** [comment]
https://github.com/Porthmeus/MeMoMe/issues/53
