### ISSUE TITLE
Db_path/config unbound

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#80]
![image](https://github.com/Porthmeus/MeMoMe/assets/7808379/be08f15a-447a-4611-b00f-aab71a7c35e1)

The variable db_path is not bound in the case that the if statement above is not being executed. Same for the config variable

**Comment by Unaimend** [comment]
https://github.com/Porthmeus/MeMoMe/blob/669b67cefe7ccfc1236a238d46d47f3f62418dfb/src/annotateChEBI.py#L20

**Comment by Porthmeus** [comment]
Is removed the if statement on my branch, will through a correct error next time. Will be merged with next PR.

**Comment by Porthmeus** [comment]
Fixed with #90
