### ISSUE TITLE
Adjust method return for annotateVMH

### ISSUE THREAD

**Issue by Unaimend** [Porthmeus/MeMoMe#82]
Currently annotateVMH only returns the amount of annotated metabs.

https://github.com/Porthmeus/MeMoMe/blob/099518aa126b4e5d59fd59f14cf1ce32c9d02409/src/annotateVMH.py#L94

Jan also added annotated names and databases to the return. If would be good if the annoatteVMH function does this as well.

See here for an example:

https://github.com/Porthmeus/MeMoMe/blob/669b67cefe7ccfc1236a238d46d47f3f62418dfb/src/annotateBiGG.py#L53

**Comment by Unaimend** [comment]
@DafniGi Please see latest Version on the main branch. Return type chanded

**Comment by DafniGi** [comment]
See [annotateVMH.py](https://github.com/Porthmeus/MeMoMe/blob/daf/bulkAnnotateVMH/src/annotateVMH.py)
